#!/usr/bin/env python3
"""Enumerate the discrete relative-block branches for w8_21.

The previous symbolic gate covered one relative-block parameter branch.  The
closed form for W admits four representative branches generated by a sign
flip of c and a pi shift.  This gate enumerates those branches, verifies that
they produce the same W, derives the induced local Clifford factor Q, and
checks the phase-ratio product for the post-context left dressing.

All four branches retain the necessary condition exp(2*i*theta)=1 for a
two-parameter Ry(ep) Rz(dp) left dressing.  This is a finite discrete-branch
closure, not a global six-parameter lower bound or a full-circuit rewrite.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
from typing import Any

import sympy as sp


METHOD = "b7_w8_21_discrete_branch_enumeration_v0"
TEMPLATE_ID = "w8_21"
SOURCE_QASM = "results/b1_u3_phase_factored_optimizer/qasmbench_medium_exact/gcm_h6.qasm"
NEIGHBORHOOD_RESULT = "results/B7_w8_21_neighborhood_transfer_v0.json"
OBSTRUCTION_RESULT = "results/B7_w8_21_context_symbolic_obstruction_v0.json"
RESULT_PATH = "results/B7_w8_21_discrete_branch_enumeration_v0.json"
REPORT_PATH = "research/B7_w8_21_discrete_branch_enumeration.md"
EXACT_TOLERANCE = 1e-12
SOURCE_E = 1.1254377896453873

I = sp.I
a, b, c, theta, d, e = sp.symbols("a b c theta d e", real=True)


def stable_hash(value: Any) -> str:
    blob = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rz(angle: sp.Expr) -> sp.Matrix:
    return sp.diag(sp.exp(-I * angle / 2), sp.exp(I * angle / 2))


def ry(angle: sp.Expr) -> sp.Matrix:
    return sp.Matrix(
        [
            [sp.cos(angle / 2), -sp.sin(angle / 2)],
            [sp.sin(angle / 2), sp.cos(angle / 2)],
        ]
    )


def relative_block(aa: sp.Expr, bb: sp.Expr, cc: sp.Expr) -> sp.Matrix:
    return sp.Matrix(
        [
            [-sp.exp(I * bb) * sp.cos(cc), -sp.exp(I * aa) * sp.sin(cc)],
            [sp.exp(-I * aa) * sp.sin(cc), -sp.exp(-I * bb) * sp.cos(cc)],
        ]
    )


def source_local_factor(aa: sp.Expr, bb: sp.Expr, cc: sp.Expr) -> sp.Matrix:
    return rz(sp.pi) * ry(cc) * rz(bb) * rz(aa)


def branches() -> list[dict[str, Any]]:
    return [
        {
            "branch_id": "s_plus_k0",
            "a_prime": a,
            "b_prime": b,
            "c_prime": c,
            "parameter_formula": "a'=a, b'=b, c'=c",
            "q_label": "I",
            "q_matrix": sp.eye(2),
        },
        {
            "branch_id": "s_plus_k1",
            "a_prime": a + sp.pi,
            "b_prime": b - sp.pi,
            "c_prime": c + sp.pi,
            "parameter_formula": "a'=a+pi, b'=b-pi, c'=c+pi",
            "q_label": "Ry(pi)",
            "q_matrix": ry(sp.pi),
        },
        {
            "branch_id": "s_minus_k0",
            "a_prime": a + sp.pi,
            "b_prime": b,
            "c_prime": -c,
            "parameter_formula": "a'=a+pi, b'=b, c'=-c",
            "q_label": "Rz(-pi)",
            "q_matrix": rz(-sp.pi),
        },
        {
            "branch_id": "s_minus_k1",
            "a_prime": a,
            "b_prime": b - sp.pi,
            "c_prime": sp.pi - c,
            "parameter_formula": "a'=a, b'=b-pi, c'=pi-c",
            "q_label": "iX",
            "q_matrix": sp.Matrix([[0, I], [I, 0]]),
        },
    ]


def matrix_equal(left: sp.Matrix, right: sp.Matrix) -> bool:
    return all(sp.simplify(left[i, j] - right[i, j]) == 0 for i in range(left.rows) for j in range(left.cols))


def branch_certificate(branch: dict[str, Any]) -> dict[str, Any]:
    aa, bb, cc = branch["a_prime"], branch["b_prime"], branch["c_prime"]
    same_w = matrix_equal(relative_block(aa, bb, cc), relative_block(a, b, c))
    induced_q = (source_local_factor(a, b, c) * source_local_factor(aa, bb, cc).conjugate().T).applyfunc(
        lambda value: sp.simplify(sp.expand_complex(value))
    )
    q_matches = matrix_equal(induced_q, branch["q_matrix"])
    left = rz(theta) * ry(e) * rz(d) * branch["q_matrix"]
    off_ratio = sp.simplify(left[1, 0] / (-left[0, 1]))
    diag_ratio = sp.simplify(left[1, 1] / left[0, 0])
    product = sp.simplify(sp.trigsimp(off_ratio * diag_ratio))
    product_matches = sp.simplify(product - sp.exp(2 * I * theta)) == 0
    return {
        "branch_id": branch["branch_id"],
        "parameter_formula": branch["parameter_formula"],
        "q_label": branch["q_label"],
        "q_matrix": [[str(branch["q_matrix"][i, j]) for j in range(2)] for i in range(2)],
        "induced_q_matrix": [[str(induced_q[i, j]) for j in range(2)] for i in range(2)],
        "offdiagonal_ratio": str(off_ratio),
        "diagonal_ratio": str(diag_ratio),
        "ratio_product": str(product),
        "exact_checks": {
            "same_relative_block": bool(same_w),
            "induced_q_matches_table": bool(q_matches),
            "phase_ratio_product_is_exp_2_i_theta": bool(product_matches),
        },
        "exact_checks_passed": sum(bool(value) for value in (same_w, q_matches, product_matches)),
        "exact_checks_total": 3,
    }


def build(root: Path) -> dict[str, Any]:
    neighborhood = json.loads((root / NEIGHBORHOOD_RESULT).read_text(encoding="utf-8"))
    obstruction = json.loads((root / OBSTRUCTION_RESULT).read_text(encoding="utf-8"))
    branch_rows = [branch_certificate(branch) for branch in branches()]
    context_rows = []
    generic_source = abs(math.sin(SOURCE_E / 2.0)) > EXACT_TOLERANCE and abs(math.cos(SOURCE_E / 2.0)) > EXACT_TOLERANCE
    for index, source_row in enumerate(neighborhood["rows"], start=1):
        angle = float(source_row["context_operation"]["angle"])
        distance = abs(complex(math.cos(2.0 * angle), math.sin(2.0 * angle)) - 1.0)
        context_rows.append(
            {
                "context_index": index,
                "direction": source_row["direction"],
                "line_span": source_row["line_span"],
                "context_operation": source_row["context_operation"],
                "theta": angle,
                "generic_source_left_dressing": generic_source,
                "exp_2_i_theta_distance_from_one": float(distance),
                "absorbing_branch_count": 0 if generic_source and distance > EXACT_TOLERANCE else len(branch_rows),
            }
        )
    exact_checks_passed = sum(row["exact_checks_passed"] for row in branch_rows)
    exact_checks_total = sum(row["exact_checks_total"] for row in branch_rows)
    source_bindings = {
        SOURCE_QASM: {"path": SOURCE_QASM, "sha256": file_sha256(root / SOURCE_QASM)},
        NEIGHBORHOOD_RESULT: {"path": NEIGHBORHOOD_RESULT, "sha256": file_sha256(root / NEIGHBORHOOD_RESULT)},
        OBSTRUCTION_RESULT: {"path": OBSTRUCTION_RESULT, "sha256": file_sha256(root / OBSTRUCTION_RESULT)},
    }
    result: dict[str, Any] = {
        "title": "B7 w8_21 discrete relative-block branch enumeration",
        "version": 0,
        "method": METHOD,
        "status": "discrete_branch_enumeration_complete_no_absorption_route",
        "classification": "finite_discrete_relative_branch_closure",
        "template_id": TEMPLATE_ID,
        "theorem": {
            "branch_count": len(branch_rows),
            "branch_rows": branch_rows,
            "exact_checks_passed": exact_checks_passed,
            "exact_checks_total": exact_checks_total,
            "forced_condition": "exp(2*i*theta) = 1",
            "real_angle_consequence": "theta = 0 mod pi",
            "generic_nonzero_conditions": ["sin(e/2) != 0", "cos(e/2) != 0"],
        },
        "source_bindings": source_bindings,
        "upstream_evidence": {
            "neighborhood_status": neighborhood["status"],
            "obstruction_status": obstruction["status"],
            "obstruction_exact_checks_passed": obstruction["theorem"]["exact_checks_passed"],
        },
        "summary": {
            "branch_count": len(branch_rows),
            "tested_context_count": len(context_rows),
            "context_branch_pairs": len(context_rows) * len(branch_rows),
            "exact_checks_passed": exact_checks_passed,
            "exact_checks_total": exact_checks_total,
            "generic_source_left_dressing_count": sum(row["generic_source_left_dressing"] for row in context_rows),
            "absorbing_context_branch_pair_count": sum(row["absorbing_branch_count"] for row in context_rows),
            "minimum_exp_2_i_theta_distance_from_one": min(row["exp_2_i_theta_distance_from_one"] for row in context_rows),
            "maximum_exp_2_i_theta_distance_from_one": max(row["exp_2_i_theta_distance_from_one"] for row in context_rows),
            "accepted_occurrence_removal": 0,
            "accepted_proxy_t_reduction": 0,
            "b7_credit": 0,
            "validation_error_count": 0,
            "rewrite_claimed": False,
            "resource_saving_claimed": False,
            "global_lower_bound_claimed": False,
        },
        "contexts": context_rows,
        "claim_boundary": {
            "supported_claim": "All four representative discrete branches preserving the closed w8_21 relative block retain the phase-ratio product exp(2*i*theta); under generic source dressing none of the seven source-bound contexts admits the declared two-parameter left-dressing absorption.",
            "unsupported_claims": [
                "No global continuous KAK lower bound is claimed.",
                "No claim is made about arbitrary Clifford scaffolds, ancillas, measurements, or full-circuit rewrites.",
                "No occurrence removal, proxy-T reduction, or B7 credit is accepted.",
            ],
            "finite_discrete_branch_set_only": True,
            "global_lower_bound_claimed": False,
            "rewrite_claimed": False,
            "resource_saving_claimed": False,
        },
        "artifacts": {"result": RESULT_PATH, "markdown_report": REPORT_PATH},
        "payload_hash": "",
    }
    result["payload_hash"] = stable_hash({key: value for key, value in result.items() if key != "payload_hash"})
    return result


def report(result: dict[str, Any]) -> str:
    theorem = result["theorem"]
    summary = result["summary"]
    lines = [
        "# B7 w8_21 Discrete Relative-Block Branch Enumeration",
        "",
        f"- Status: `{result['status']}`",
        f"- Classification: `{result['classification']}`",
        f"- Branches enumerated: `{summary['branch_count']}`",
        f"- Exact branch checks: `{summary['exact_checks_passed']}/{summary['exact_checks_total']}`",
        f"- Context-branch pairs: `{summary['context_branch_pairs']}`",
        f"- Absorbing pairs: `{summary['absorbing_context_branch_pair_count']}/{summary['context_branch_pairs']}`",
        f"- Payload hash: `{result['payload_hash']}`",
        "",
        "## Heuristic question",
        "",
        "Can a hidden pi-shift or sign-flip branch evade the phase-ratio obstruction without paying for another parameter or CNOT?",
        "",
        "## Finite branch closure",
        "",
        "The closed relative block admits four representative branches, generated by `c'=s*c+k*pi` with `s` in `{+1,-1}` and `k` in `{0,1}`. Their induced factors are `I`, `Ry(pi)`, `Rz(-pi)`, and `iX` respectively.",
        "",
        "| Branch | Parameter relation | Induced Q | Same W | Ratio product |",
        "|---|---|---|---:|---:|",
    ]
    for row in theorem["branch_rows"]:
        checks = row["exact_checks"]
        lines.append(f"| `{row['branch_id']}` | `{row['parameter_formula']}` | `{row['q_label']}` | {str(checks['same_relative_block'])} | `{row['ratio_product']}` |")
    lines.extend(
        [
            "",
            "Every branch gives the same exact ratio product `exp(2*i*theta)`. For real angles, a two-parameter `Ry(ep) Rz(dp)` left dressing can therefore match only when `theta=0 mod pi`, provided the source left dressing is generic.",
            "",
            "## Source-bound check",
            "",
            f"The enumeration binds `{summary['context_branch_pairs']}` context-branch pairs across `{summary['tested_context_count']}` real contexts. Generic source dressing appears in `{summary['generic_source_left_dressing_count']}/{summary['tested_context_count']}` contexts. The distance from `exp(2*i*theta)=1` ranges from `{summary['minimum_exp_2_i_theta_distance_from_one']:.16g}` to `{summary['maximum_exp_2_i_theta_distance_from_one']:.16g}`; absorbing pairs are `{summary['absorbing_context_branch_pair_count']}/{summary['context_branch_pairs']}`.",
            "",
            "## Claim boundary",
            "",
            "This closes the four representative discrete branches of the declared relative-block parameterization. It is not a global continuous KAK lower bound, not an exhaustive Clifford-frame theorem, and not a full-circuit rewrite. Accepted occurrence removal, proxy-T reduction, and B7 credit remain zero.",
            "",
            "## Next route",
            "",
            "The remaining escape route is continuous: search a genuinely different nonlocal scaffold or prove a broader invariant statement that covers more than the target-only two-CX family.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--json-output", type=Path, default=Path(RESULT_PATH))
    parser.add_argument("--markdown-output", type=Path, default=Path(REPORT_PATH))
    args = parser.parse_args()
    root = args.root.resolve()
    result = build(root)
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.write_text(report(result), encoding="utf-8")
    print(json.dumps({"status": result["status"], "payload_hash": result["payload_hash"], **result["summary"]}, sort_keys=True))


if __name__ == "__main__":
    main()
