#!/usr/bin/env python3
"""Emit a symbolic/proof-assistant skeleton for the B9 failed gap lemma."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


LEAN_PREAMBLE = """-- B9 symbolic failed gap-amplification skeleton v0.1
-- Generated by tools/b9_symbolic_gap_skeleton.py
-- This file is a proof skeleton with admitted obligations, not a formal proof.

import Mathlib.Data.Real.Basic

namespace B9

structure LocalHamiltonianFamily where
  n : Nat
  locality : Nat
  spectralGap : Real
  spectralWidth : Real
  normalizedGap : Real
  groundOverlap : Real

structure LocalTransform where
  localityPreserving : Prop
  widthBounded : Prop
  groundStable : Prop

def RawGapAmplifies (before after : LocalHamiltonianFamily) : Prop :=
  after.spectralGap > before.spectralGap

def NormalizedGapAmplifies (before after : LocalHamiltonianFamily) : Prop :=
  after.normalizedGap > before.normalizedGap

def AcceptableLocalGapStep (before after : LocalHamiltonianFamily) (T : LocalTransform) : Prop :=
  T.localityPreserving ∧ T.widthBounded ∧ T.groundStable ∧ NormalizedGapAmplifies before after
"""


LEAN_THEOREMS = """theorem raw_gap_growth_not_certificate
    (before after : LocalHamiltonianFamily)
    (T : LocalTransform)
    (hRaw : RawGapAmplifies before after)
    (hNoNorm : ¬ NormalizedGapAmplifies before after) :
    ¬ AcceptableLocalGapStep before after T := by
  intro hAccept
  exact hNoNorm hAccept.right.right.right

theorem dense_filter_not_local_step
    (before after : LocalHamiltonianFamily)
    (T : LocalTransform)
    (hNotLocal : ¬ T.localityPreserving) :
    ¬ AcceptableLocalGapStep before after T := by
  intro hAccept
  exact hNotLocal hAccept.left

-- Open obligation: instantiate this symbolic skeleton for the named B9 v0
-- finite families, replacing finite JSON rows with an analytic width/locality
-- argument over a parameterized Hamiltonian family.
theorem b9_v0_family_width_locality_obligation :
    True := by
  trivial

end B9
"""


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def validate_report(report: dict) -> list[str]:
    errors: list[str] = []
    if report.get("status") != "symbolic_proof_skeleton_not_formalized_theorem":
        errors.append("status must identify symbolic skeleton as not formalized theorem")
    if report.get("source_method") != "b9_failed_gap_amplification_negative_lemma_v0":
        errors.append("source method mismatch")
    if int(report.get("symbolic_definition_count", 0)) < 4:
        errors.append("skeleton should define the key symbolic predicates")
    if int(report.get("theorem_skeleton_count", 0)) < 3:
        errors.append("skeleton should contain at least three theorem skeletons")
    if int(report.get("open_obligation_count", 0)) < 5:
        errors.append("skeleton should preserve the five open proof obligations")
    if report.get("proof_assistant_target") != "Lean-style skeleton":
        errors.append("proof assistant target should be recorded")
    if report.get("proof_assistant_checked") is not False:
        errors.append("proof assistant checked must remain false")
    if report.get("formal_theorem_proved") is not False:
        errors.append("formal theorem proved must remain false")
    if report.get("explicit_not_quantum_pcp_proof") is not True:
        errors.append("skeleton must explicitly avoid Quantum PCP proof claims")
    if report.get("global_gap_amplification_impossibility_claimed") is not False:
        errors.append("skeleton must not claim global impossibility")
    if len(report.get("validation_errors", [])) != 0:
        errors.append("nested validation errors should be empty before finalization")
    return errors


def lean_source(source: dict) -> str:
    obligations = source.get("proof_obligations", [])
    lines = [LEAN_PREAMBLE, "", "-- Source proof obligations carried from finite-instance lemma:"]
    for idx, item in enumerate(obligations, start=1):
        lines.append(f"-- O{idx}: {item}")
    lines.extend(["", LEAN_THEOREMS])
    return "\n".join(lines)


def run(source_path: Path, lean_output: Path) -> dict:
    source = load_json(source_path)
    lean_text = lean_source(source)
    theorem_skeleton_names = [
        "raw_gap_growth_not_certificate",
        "dense_filter_not_local_step",
        "b9_v0_family_width_locality_obligation",
    ]
    symbolic_definitions = [
        "LocalHamiltonianFamily",
        "LocalTransform",
        "RawGapAmplifies",
        "NormalizedGapAmplifies",
        "AcceptableLocalGapStep",
    ]
    report = {
        "benchmark_id": "B9",
        "problem_id": 17,
        "title": "B9 symbolic failed gap-amplification proof skeleton",
        "version": "0.1",
        "last_updated": "2026-06-17",
        "status": "symbolic_proof_skeleton_not_formalized_theorem",
        "method": "b9_symbolic_gap_amplification_skeleton_v0",
        "source_result": str(source_path),
        "source_method": source.get("method"),
        "source_status": source.get("status"),
        "proof_assistant_target": "Lean-style skeleton",
        "lean_skeleton_output": str(lean_output),
        "symbolic_definitions": symbolic_definitions,
        "symbolic_definition_count": len(symbolic_definitions),
        "theorem_skeleton_names": theorem_skeleton_names,
        "theorem_skeleton_count": len(theorem_skeleton_names),
        "open_obligations": source.get("proof_obligations", []),
        "open_obligation_count": len(source.get("proof_obligations", [])),
        "strict_counterexample_count_inherited": source.get("strict_counterexample_count"),
        "dense_locality_trap_count_inherited": source.get("dense_locality_trap_count"),
        "proof_assistant_checked": False,
        "formal_theorem_proved": False,
        "explicit_not_quantum_pcp_proof": True,
        "global_gap_amplification_impossibility_claimed": False,
        "claim_boundary": [
            "Supported: a Lean-style symbolic skeleton that separates raw-gap, normalized-gap, locality, and ground-stability obligations.",
            "Not supported: proof-assistant checked theorem, Quantum PCP proof, NLTS theorem, or global gap-amplification no-go theorem.",
        ],
        "next_steps": [
            "Replace the abstract LocalHamiltonianFamily fields with a parameterized Hamiltonian family.",
            "Prove an analytic spectral-width bound for the chosen transformation.",
            "Prove term-by-term locality preservation or mark the transformation invalid.",
            "Connect finite counterexample rows to symbolic assumptions via generated certificates.",
            "Run a real Lean/mathlib check once the definitions are concrete.",
        ],
    }
    report["validation_errors"] = validate_report({**report, "validation_errors": []})
    return report


def markdown(report: dict) -> str:
    lines = [
        "# B9 Symbolic Failed Gap-Amplification Skeleton v0.1",
        "",
        "Last updated: 2026-06-17",
        "",
        f"Status: **{report['status']}**",
        "",
        "## Summary",
        "",
        f"- Source method: {report['source_method']}",
        f"- Proof assistant target: {report['proof_assistant_target']}",
        f"- Lean-style skeleton: `{report['lean_skeleton_output']}`",
        f"- Symbolic definitions: {report['symbolic_definition_count']}",
        f"- Theorem skeletons: {report['theorem_skeleton_count']}",
        f"- Open obligations: {report['open_obligation_count']}",
        f"- Inherited strict counterexamples: {report['strict_counterexample_count_inherited']}",
        f"- Inherited dense locality traps: {report['dense_locality_trap_count_inherited']}",
        f"- Proof assistant checked: {report['proof_assistant_checked']}",
        f"- Formal theorem proved: {report['formal_theorem_proved']}",
        f"- Explicitly not Quantum PCP proof: {report['explicit_not_quantum_pcp_proof']}",
        f"- Global impossibility claimed: {report['global_gap_amplification_impossibility_claimed']}",
        f"- Validation errors: {len(report['validation_errors'])}",
        "",
        "## Symbolic Definitions",
        "",
    ]
    lines.extend(f"- `{item}`" for item in report["symbolic_definitions"])
    lines.extend(["", "## Theorem Skeletons", ""])
    lines.extend(f"- `{item}`" for item in report["theorem_skeleton_names"])
    lines.extend(["", "## Open Obligations", ""])
    lines.extend(f"- {item}" for item in report["open_obligations"])
    lines.extend(["", "## Claim Boundary", ""])
    lines.extend(f"- {item}" for item in report["claim_boundary"])
    lines.extend(["", "## Next Steps", ""])
    lines.extend(f"- {item}" for item in report["next_steps"])
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path("results/B9_failed_gap_amplification_lemma_v0.json"))
    parser.add_argument("--lean-output", type=Path, default=Path("research/proof_skeletons/B9_failed_gap_amplification_skeleton.lean"))
    parser.add_argument("--json-output", type=Path, default=Path("results/B9_symbolic_gap_skeleton_v0.json"))
    parser.add_argument("--markdown-output", type=Path, default=Path("research/B9_symbolic_gap_skeleton.md"))
    parser.add_argument("--pretty", action="store_true")
    args = parser.parse_args()

    report = run(args.source, args.lean_output)
    args.lean_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.lean_output.write_text(lean_source(load_json(args.source)), encoding="utf-8")
    args.json_output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown_output.write_text(markdown(report), encoding="utf-8")
    if args.pretty:
        print(
            json.dumps(
                {
                    "status": report["status"],
                    "symbolic_definition_count": report["symbolic_definition_count"],
                    "theorem_skeleton_count": report["theorem_skeleton_count"],
                    "open_obligation_count": report["open_obligation_count"],
                    "validation_error_count": len(report["validation_errors"]),
                },
                indent=2,
                sort_keys=True,
            )
        )
    return 1 if report["validation_errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
